# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# --------------------------------------------------------------------------------------------

from knack.help_files import helps

# pylint: disable=line-too-long

helps['logicapp create'] = """
type: command
short-summary: Create a logic app.
long-summary: The logic app's name must be able to produce a unique FQDN as AppName.azurewebsites.net.
examples:
  - name: Create a basic logic app.
    text: >
        az logicapp create -g MyResourceGroup --subscription MySubscription -p MyPlan -n MyUniqueAppName -s MyStorageAccount
  
  - name: Create a logic app in Azure Arc.
    text: >
        az logicapp create -g MyResourceGroup --subscription MySubscription --name MyUniqueAppName --storage-account MyStorageAccount 
        --custom-location MyCustomLocation [--plan MyPlan]
  - name: Create a basic logic app in Azure Arc using private ACR image.
    text: >
        az logicapp create -g MyResourceGroup --name MyUniqueAppName --subscription MySubscription --storage-account MyStorageAccount
        --custom-location MyCustomLocation 
        --deployment-container-image-name myacr.azurecr.io/myimage:tag
        --docker-registry-server-password passw0rd --docker-registry-server-user MyUser [--plan MyPlan]
"""

helps['logicapp delete'] = """
type: command
short-summary: Delete a logic app.
examples:
  - name: Delete a logic app. (autogenerated)
    text: az logicapp delete --name MyLogicapp --resource-group MyResourceGroup --subscription MySubscription
    crafted: true
"""

helps['logicapp deployment source config-zip'] = """
type: command
short-summary: Perform deployment using the kudu zip push deployment for a logic app.
examples:
  - name: Perform deployment by using zip file content.
    text: >
        az logicapp deployment source config-zip \\
            -g {myRG} -n {myAppName} --subscription MySubscription \\
            --src {zipFilePathLocation}
"""

helps['logicapp restart'] = """
type: command
short-summary: Restart a logic app.
examples:
  - name: Restart a logic app. (autogenerated)
    text: az logicapp restart --name MyLogicapp --resource-group MyResourceGroup --subscription MySubscription
    crafted: true
"""

helps['logicapp show'] = """
type: command
short-summary: Get the details of a logic app.
examples:
  - name: Get the details of a logic app. (autogenerated)
    text: az logicapp show --name MyLogicapp --resource-group MyResourceGroup --subscription MySubscription
    crafted: true
"""

helps['logicapp start'] = """
type: command
short-summary: Start a logic app.
examples:
  - name: Start a logic app. (autogenerated)
    text: az logicapp start --name MyLogicapp --resource-group MyResourceGroup --subscription MySubscription
    crafted: true
"""

helps['logicapp stop'] = """
type: command
short-summary: Stop a logic app.
examples:
  - name: Stop a logic app. (autogenerated)
    text: az logicapp stop --name MyLogicapp --resource-group MyResourceGroup --subscription MySubscription
    crafted: true
"""
helps['logicapp scale'] = """
type: command
short-summary: Scale a logic app.
examples:
  - name: Scale a logic app. (autogenerated)
    text: az logicapp scale --name MyLogicapp --resource-group --subscription MySubscription MyResourceGroup --instance-count 3
    crafted: true
"""

helps['logicapp config appsettings'] = """
type: group
short-summary: Configure logic app settings.
"""

helps['logicapp config appsettings delete'] = """
type: command
short-summary: Delete a logic app's settings.
examples:
  - name: Delete a logic app's settings. (autogenerated)
    text: az logicapp config appsettings delete --name MyLogicApp --resource-group MyResourceGroup --subscription MySubscription --setting-names {setting-names}
    crafted: true
"""

helps['logicapp config appsettings list'] = """
type: command
short-summary: Show settings for a logic app.
examples:
  - name: Show settings for a logic app. (autogenerated)
    text: az logicapp config appsettings list --name MyWebapp --resource-group MyResourceGroup --subscription MySubscription
    crafted: true
"""

helps['logicapp config appsettings set'] = """
type: command
short-summary: Update a logic app's settings.
examples:
  - name: Update a logic app's settings.
    text: |
        az logicapp config appsettings set --name MyLogicApp --resource-group MyResourceGroup --subscription MySubscription --settings "AzureWebJobsStorage=$storageConnectionString"
"""
